OUTPUT_DIR: ./outputs/phys
DATA_ROOT: 'data/simb_split/'
DATASET_ABS: 'SimB'
SOLVER:
  BASE_LR: 1.0e-4  # single GPU LR
  WEIGHT_DECAY: 1.0e-6
  SCHEDULER: 'cosine'
  MAX_ITERS: 2000000
  WARMUP_ITERS: 40000
  VAL_INTERVAL: 200000
  BATCH_SIZE: 20 # single GPU Batch Size
INPUT:
  IMAGE_MEAN: [0, 0, 0]
  IMAGE_STD: [1, 1, 1]
  PRELOAD_TO_MEMORY: False
  IMAGE_CHANNEL: 2
RPIN:
  BACKBONE: 'hourglass_bn'
  ARCH: 'rpcin'
  VE_FEAT_DIM: 256
  IN_FEAT_DIM: 256
  # prediction setting:
  INPUT_SIZE: 4
  PRED_SIZE_TRAIN: 20
  PRED_SIZE_TEST: 40
  # input setting:
  INPUT_HEIGHT: 96
  INPUT_WIDTH: 192
  MAX_NUM_OBJS: 3
  # data augmentation
  HORIZONTAL_FLIP: True
  VERTICAL_FLIP: True
  # loss weight
  POSITION_LOSS_WEIGHT: 1
  # ----- RoIPooling Setting
  ROI_POOL_SIZE: 3
  # ----- mask prediction
  MASK_LOSS_WEIGHT: 0.000
  # ----- Architecture
  N_EXTRA_ROI_F: 2
  N_EXTRA_PRED_F: 0
  N_EXTRA_SELFD_F: 0
  N_EXTRA_RELD_F: 0
  N_EXTRA_AFFECTOR_F: 0
  N_EXTRA_AGGREGATOR_F: 0
  IMAGE_EXT: '.pkl'
  TRAIN_MODE: 'env_mask'